"""add_column_positionid_employee_table

Revision ID: e754bb7ab5ed
Revises: 9b4d3fc7ba87
Create Date: 2023-04-12 16:12:17.375623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e754bb7ab5ed'
down_revision = '9b4d3fc7ba87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'position', ['position_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('position_id')

    # ### end Alembic commands ###
